database:
  host: 127.0.0.1
  port: 3306
  username: goload
  password: goload
  database: goload
cache:
  type: "redis"
  address: 127.0.0.1:6379
  username: goload
  password: goload
mq:
  addresses:
    - 127.0.0.1:9092
  client_id: "go_load"
auth:
  hash:
    cost: 10
  token:
    expires_in: 24h
    regenerate_token_before_expiry: 1h
grpc:
  address: "0.0.0.0:8080"
http:
  address: "0.0.0.0:8081"
